NAME_ASTROSAUCE = "Астросоус"
NAME_COSMOSAUCE = "Соус космический"
PRICE_ASTROSAUCE = 150
PRICE_COSMOSAUCE = 200000

NAME_FILLING_VULKAN_CUTLET = "Вулканичечска котлета"
NAME_FILLING_SALAD_MARS = "Салат с марса"
PRICE_VULKAN_CUTLET = 100.5
PRICE_SALAD_MARS = 1

NAME_BUN_COSMO = "Космобулка"
NAME_BUN_BLACK_BUN = "BLACK BUN"
NAME_BUN_NO_NAME = ""

PRICE_BUN_INT = 150
PRICE_BUN_FLOAT = 101.5
PRICE_BUN_LARGE = 5000000
