BUN_CIABATTA = 'ciabatta'
BUN_BAP = 'bap'
BUN_BAGEL = 'bagel'

INGREDIENT_TYPE_DEFAULT = 'default_type'

INGREDIENT_HAM = 'ham'
INGREDIENT_CHEESE = 'cheese'
INGREDIENT_NAME_DEFAULT = 'default name'

INGREDIENT_SAUCE_TABASCO = 'tabasco'
INGREDIENT_SAUCE_TOMATO = 'tomato'
INGREDIENT_SAUCE_DEFAULT = 'default souse name'

PRICE_DEFAULT = 100
PRICE_ZERO = 0
PRICE_FLOAT = 50.5
PRICE_INT = 100

MOCK_BUN_PRICE = 75
MOCK_INGREDIENT_SAUCE_PRICE = 25
MOCK_INGREDIENT_FILLING_PRICE = 50
